name: Assign to Project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  assign-to-project:
    permissions:
      repository-projects: write  # for srggrs/assign-one-project-github-action to assign issues and PRs to repo project
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - name: Assign Issues to Bugs
      uses: srggrs/assign-one-project-github-action@65a8ddab497df42ef268001e67bbf976f8fd39e1
      if: contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/irongut/CodeCoverageSummary/projects/1'
        column_name: 'Needs triage'

    - name: Assign Issues to Enhancements
      uses: srggrs/assign-one-project-github-action@65a8ddab497df42ef268001e67bbf976f8fd39e1
      if: contains(github.event.issue.labels.*.name, 'enhancement')
      with:
        project: 'https://github.com/irongut/CodeCoverageSummary/projects/2'
        column_name: 'To do'

    - name: Assign PRs to Bugs
      uses: srggrs/assign-one-project-github-action@65a8ddab497df42ef268001e67bbf976f8fd39e1
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      with:
        project: 'https://github.com/irongut/CodeCoverageSummary/projects/1'
        column_name: 'In Progress'

    - name: Assign PRs to Enhancements
      uses: srggrs/assign-one-project-github-action@65a8ddab497df42ef268001e67bbf976f8fd39e1
      if: contains(github.event.pull_request.labels.*.name, 'enhancement')
      with:
        project: 'https://github.com/irongut/CodeCoverageSummary/projects/2'
        column_name: 'In Progress'
