# Assign PR to Author
# https://github.com/samspills/assign-pr-to-author

name: Auto Assign PR
on: [pull_request]

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Assign PR
      uses: samspills/assign-pr-to-author@v1.0
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
