name: Test Linux Runner

on:
  workflow_dispatch:
permissions:
  contents: read  

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Test Action
      uses: irongut/CodeCoverageSummary@master
      with:
        filename: /app/sample.coverage.xml
        badge: true
        fail_below_min: true
        format: 'markdown'
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: 'both'
        thresholds: '60 80'
